### PR TITLE
Adding support for other schema(s)

### PR DESCRIPTION
**Pull request by erlinghaugstad**
Schema name will be prepended to all schema(s) other than public. This will support having the same table name in public and in other schema(s).

Note that public will still not be appended to the tables in the public schema.

### CODE REVIEW

**Comment by koistya** [comment]
@erlinghaugstad amazing!

BTW, do you think we can rename `includedSchemas` to `schemas`?

Down the road, if we can allow excluding schemas like this:

- `updateTypes(db, {})` - generates types for the `public` schema only (default)
- `updateTypes(db, { schemas: ["public", "log"] })` - generates types for "public" and "log" schemas
- `updateTypes(db, { schemas: ["!log"] }` - generates types for all schemas excluding "log"

**Comment by erlinghaugstad** [comment]
Sure, i can fix your suggested change to inclusion/exclusion of schemas as well 👍🏻 

I was pondering if public should always be included, or only by default and if you specify something you would have to include it. I guess that i still the case, and that it still makes sense.

**Comment by erlinghaugstad** [comment]
Should all be in now, if this is a success 🤞🏻

**Comment by erlinghaugstad** [comment]
One note, this should solve all except the last bullet point _"..generates types for all schemas excluding..."_, should we wait until we need it?

**Comment by koistya** [comment]
@erlinghaugstad yep, agreed, excluding schemas can wait until we need it.

**Pull request merged**
